<?php
global $test;
global $test;
global $test;
global $test;
global $test;
global $test;
ob_start();
?>
<!DOCTYPE html>
<html>
    <head>
        <title>Test title</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <div><?php echo isset($test) ? $test : ""; ?></div>
        <div>\{{test}}</div>
        <div><?php echo isset($test) ? $test : ""; ?></div>
        <div><?php echo isset($test) ? $test : ""; ?></div>
        <div>\{{test}}</div>
        <div><?php echo isset($test) ? $test : ""; ?></div>
        <div><?php echo isset($test) ? $test : ""; ?></div>
        <div>\{{test}}</div>
        <div><?php echo isset($test) ? $test : ""; ?></div>
    </body>
</html>
